IgorPattern
	::= ComplexPattern
	| SubjectPattern (Combinator ComplexPattern)?

SubjectPattern
	::= ComplexPattern "!"

ComplexPattern
	::= CompoundPattern (Combinator CompoundPattern)*

CompoundPattern
	::= NodePattern | "(" ComplexPattern ")"

Combinator
	::= S ( Whitespace | ">" | "~") S

NodePattern
	::= ClassTest InstanceTest*
	| InstanceTest+

ClassTest
	::= ClassName
	| ClassName "*"
	| "*"

InstanceTest
	::= "#" Identifier
	| ":" PositionTest
	| "[" Predicate "]"

Identifier
	::= Integer | Word | String

S	::= Whitespace?
