"Igor Query Language" {

Selector
	= ComplexPattern [ '!' [ Combinator ComplexPattern ] ]
	;

ComplexPattern
	= { SubjectPattern Combinator } SubjectPattern
	;

SubjectPattern
	= NodePattern
	| BranchPattern
	;

BranchPattern
	= '(' ComplexPattern ')'
	;

NodePattern
	= ( ClassSelector | InstanceSelector ) { InstanceSelector }
	;

ClassPattern
	= ClassName
	| ClassName '*'
	| '*'
	;

InstancePattern
	= IdentifierPattern
	| PositionSelector
	| PredicateSelector
	;

IdentifierPattern
	= '#' Identifier
	;

PositionPattern
	= ':' Position
	;

PredicatePattern
	= '[' Predicate ']'
	;

Identifier
	= Integer
	| Word
	| String
	;

Combinator
	= Whitespace
	| '>'
	| '~'
	;
}
